Allow capacitors to recharge Baubles items
CoFH/ThermalExpansion-1.12-Legacy pull request #9
Opened 2017-08-19 12:11 UTC by KaseiFR

2017-08-19 14:41 UTC, covers1624 requested changes
Looks good to me, some minor style changes are needed.

2017-08-19 14:41 UTC, covers1624 commented on src/main/java/cofh/thermalexpansion/item/ItemCapacitor.java
> +		if (CAPABILITY_BAUBLES == null) {
New line after method deceleration.

2017-08-19 14:41 UTC, covers1624 commented on src/main/java/cofh/thermalexpansion/item/ItemCapacitor.java
> +				.collect(Collectors.toList());
probably add some ninja comments here so our formatters don't one line it again.

2017-08-19 14:52 UTC, KaseiFR commented
Done. I don't know the param of your formatter, so I hope it will like it this way.

2017-08-19 14:57 UTC, covers1624 commented
You'll have to whack one on each line, just a simple `//` should do, unless lemming is fine with it being smushed to one line and we drop the ninja comments all together.

2017-08-19 17:17 UTC, KaseiFR commented
I've added the fake comments

2017-08-25 12:48 UTC, KingLemming commented
This is only a soft dep right? TE won't depend on Baubles being present?

2017-08-25 12:49 UTC, covers1624 approved these changes

2017-08-25 14:18 UTC, miuirussia commented
Looks like it has hard dependency for Baubles

2017-08-25 16:37 UTC, KaseiFR commented
No, it's not a hard dependency, and I've tested it.  
If Baubles is not present, the capability is never injected and the code depending on Baubles is never reached.

2017-08-25 16:58 UTC, covers1624 commented
Hmm, i was sure that the JVM would try and define every class used in a method when called. Lemme test this myself.

2017-08-25 17:10 UTC, covers1624 commented
Well seems i was wrong. Good to merge.

2017-08-25 17:15 UTC, KaseiFR commented
Can't blame you, the JVM is weird. And it's the first time I found a positive side to type erasure: I think I can only manipulate the capability because its generic type has been erased.

2017-08-25 17:17 UTC, covers1624 commented
Yeah, The generic isn't erased, its essentially just metadata for compile time and reflection, the JVM doesn't care about it when defining a class.

2017-08-27 01:24 UTC, KingLemming commented
Alright. We're gonna try this out.

2017-08-27 01:24 UTC, merged

2017-12-07 04:15 UTC, KingLemming commented
@KaseiFR - do you have a twitter handle?

2017-12-07 17:39 UTC, KaseiFR commented
Nope